apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-node-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "namespaces", deployments", "replicasets", "statefulsets", "pods/log"]
  verbs: ["get", "list", "watch", "delete", "create"]
- apiGroups: ["apps"]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "namespaces", deployments", "replicasets", "statefulsets", "pods/log"]
  verbs: ["get", "list", "watch", "delete", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-node-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-node-clusterrole
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
